### ISSUE TITLE
Change helm charts with storage/PVCs to StatefulSets

### ISSUE THREAD

**Issue by dnauck** [rancher/charts#10]
Every helm chart with persistent storage has issues to be a deployment instead of a stateful set.

E.g. if you're using longhorn storage with the wordpress (and mariadb) helm chart you cannot upgrade because the rolling upgrade waits for the storage that is used by the old pods.

Even with NFS storage you'Re in trouble when the new database pod is accessing the same files as the old running pod.

See:
https://github.com/rancher/longhorn/issues/85
https://github.com/rancher/rancher/issues/13944
https://github.com/kubernetes/charts/issues/1863

//cc @yasker

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
