### ISSUE TITLE
redis chart detailed description about persistence is incorrect.

### ISSUE THREAD

**Issue by ldbl** [rancher/charts#123]
This is not correct in detailed description in redis chart:
**By default, the chart persists both data and configuration.** 
If you wish to persist only the data directory set persistence.path to /bitnami/redis/data and persistence.subPath to redis/data.
When you hit preview you see this ```## The path the volume will be mounted at, useful when using different
    ## Redis images.
    path: /bitnami/redis/data```
it's the same when you login to the redis master.
So by default it persist only *data*.
```I have no name!@redis-master-0:/$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          46G  6.3G   39G  14% /
tmpfs           848M     0  848M   0% /dev
tmpfs           848M     0  848M   0% /sys/fs/cgroup
/dev/sda1        46G  6.3G   39G  14% /etc/hosts
shm              64M     0   64M   0% /dev/shm
/dev/sdc        7.9G   36M  7.8G   1% /bitnami/redis/data
tmpfs           848M   12K  848M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           848M     0  848M   0% /sys/firmware
I have no name!@redis-master-0:/$```

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
