### ISSUE TITLE
Failed to install cert-manager no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by exocode** [rancher/charts#1345]
I try to install `cert-manager` on my `Rancher v2.5.8`. I use the preinstalled charts

I create a **cluster** with `v1.20.8-rancher1-1`

- I add` cert-manager` with all prefilled form fields and **only add the my Email address**
- Then click save
- Wait some seconds:
- Error appears:

`Failed to install app cert-manager. Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"
`

**Cert-manager** version: `Version v0.5.2`

|Component | Version|
-- | --|
|Rancher | v2.5.8|
|User Interface | v2.5.8|
|Helm | v2.16.8-rancher1|
|Machine | v0.15.0-rancher55|

It seems these are the lines: 

`apiVersion: apps/v1beta1`

https://github.com/helm/charts/blob/f4f301ae450101b981805bd045451f08c0d74afa/stable/cert-manager/templates/deployment.yaml#L1

and so on... 

https://github.com/helm/charts/blob/f4f301ae450101b981805bd045451f08c0d74afa/stable/cert-manager/templates/rbac.yaml#L2

**How get cert-manager installed?**

Do I have to activate a feature?

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
