### ISSUE TITLE
Symbols in generated passwords can break the deployment of Wordpress

### ISSUE THREAD

**Issue by displague** [rancher/charts#143]
The password generator produces symbols that break the manifest preventing the deployment from succeeding.  The generated password characters should be restricted.

I have seen this on the Wordpress library chart fairly regularly.  I've learned to keep clicking regenerate until an all alpha-numeric password is reached.

I imagine this would affect other catalog items.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
