### ISSUE TITLE
PHPBB Chart should include L4 Loadbalancing options

### ISSUE THREAD

**Issue by displague** [rancher/charts#144]
I would argue that all of the Rancher Library charts should be generally consistent about the Loadbalancer options.

Specifically, the PHPBB chart only includes the L7 option.

**Comment by guangbochen** [comment]
updated in https://github.com/rancher/charts/tree/master/charts/phpbb/v6.0.1, and you can always customize the answers via `Edit as YAML` option if it not available by the `questions.yml`, thanks

**Comment by guangbochen** [comment]
updated in https://github.com/rancher/charts/tree/master/charts/phpbb/v6.0.1, and you can always customize the answers via `Edit as YAML` option if it not available by the `questions.yml`, thanks

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
