### ISSUE TITLE
Making sense of the vSphere chart versioning

### ISSUE THREAD

**Issue by braunsonm** [rancher/charts#1632]
Hello,

I'm trying to get this fix in my cluster: https://github.com/rancher/rancher/issues/34797

On Rancher 2.6.2 I have the following versions:
- 100.0.1
- 100.0.0 (current)
- 2.3.0
- 2.1.000

What is this versioning scheme? What should one be upgrading to?
Kube Version 1.21.5 RKE2

cc @PennyScissors

**Comment by UnstoppableMango** [comment]
Many charts seem to have this versioning scheme now. It's very confusing, and this is the only issue I've been able to find (so far) that mentions it..

FWIW I recently upgraded longhorn from 1.2.200+up1.2.2 (which no longer exists somehow) to 100.1.0+up1.2.2 and nothing significant seems to have changed. The version in the longhorn UI still shows 1.2.2 and the rancher apps and marketplace view is satisfied that it has been "upgraded" to the latest version.

The 100.* versions appear to be the "latest" as far as I can tell

**Comment by PennyScissors** [comment]
@braunsonm to get that fix in a Rancher 2.6 setup you will need to install CSI `100.1.0+up2.3.0` and pair it with CPI `100.1.0+up1.0.100`. We are actively working on improving our versioning, but as it is currently, the `100.*` charts are charts found in the Rancher 2.6 version line only and the `+up<version>` in the case of vSphere represents the version of the equivalent chart in the Rancher 2.5 version line. So in a Rancher 2.5 setup you would need to install CSI `2.3.0` and CPI `1.0.100` instead. I hope this helps.

**Comment by braunsonm** [comment]
Thank you @PennyScissors much appreciated, that does clear it up. 

The only thing that still isn't clear is how can you relate a chart like the CSI one, to a vSphere CSI version? (Like 1.22.1 for example)

It seems the images are re-tagged with the helm version and don't point to the actual upstream vSphere versions of the images. This makes it confusing to understand which features you can use (because you don't know what version of the CSI that 100.1.0 has)

**Comment by PennyScissors** [comment]
@braunsonm Our vSphere charts are based on manifests from upstream, so in some cases it's a bit challenging to figure out which version of the manifests our chart is based on. However, like you mentioned, the images is what really matters and that is easy to figure out because we mirror all the images used in our charts. 

Take `CSI 100.1.0+up2.3.0` for example, you can see what mirrored images are being used in the values.yaml [here](https://github.com/rancher/charts/blob/b35ff06e9138b1f221f1b51465755af7ac0ba797/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0%2Bup2.3.0/values.yaml#L27-L43). Then check our list of mirrored images [here](https://github.com/rancher/image-mirror/blob/master/images-list) to see what's the exact source of the mirred image. In most cases you don't really need to check that file because we follow a `rancher/mirrored-<org>-<repo>` naming pattern and use the same tag from the source. What this means is a source image `gcr.io/cloud-provider-vsphere/csi/release/driver:v2.3.0` would be mirrored to `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.3.0` which you can find in this [line](https://github.com/rancher/image-mirror/blob/6fb5954a66ba9fe4d3d9230efc4fc55706e86df2/images-list#L81) (the order is `<original-image-name> <rancher-image-name> <image-tag>`).

**Comment by PennyScissors** [comment]
@braunsonm Our vSphere charts are based on manifests from upstream (not a chart like most of the other Rancher charts), so in some cases it's a bit challenging to figure out which version of the manifests one of our chart is based on, unfortunately. However, like you mentioned, you can identify them based on the images and that is easy to figure out because we mirror all the images used in our charts so it's a matter of finding the source of the mirrored image. 

Take `CSI 100.1.0+up2.3.0` for example, you can see what mirrored images are being used in the values.yaml [here](https://github.com/rancher/charts/blob/b35ff06e9138b1f221f1b51465755af7ac0ba797/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0%2Bup2.3.0/values.yaml#L27-L43). Then check our list of mirrored images [here](https://github.com/rancher/image-mirror/blob/master/images-list) to see what's the exact source of the mirrored image and compare with the upstream manifests. In most cases you don't really need to check that file because we follow a `rancher/mirrored-<org>-<repo>` naming pattern and use the same tag from the source. What this means is a source image `gcr.io/cloud-provider-vsphere/csi/release/driver:v2.3.0` would be mirrored and named `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.3.0` which you can see in this [line](https://github.com/rancher/image-mirror/blob/6fb5954a66ba9fe4d3d9230efc4fc55706e86df2/images-list#L81) (the order is `<original-image-name> <rancher-image-name> <image-tag>`).
