### ISSUE TITLE
[charts/kafka] Update to newer version

### ISSUE THREAD

**Issue by chenjr0719** [rancher/charts#175]
Hi there,

The chart of Kafka at helm/incubator is a newer version with better external access support. Is it possible to update the chart in this repository to the newer version?

**Comment by guangbochen** [comment]
I think u can still use the helm/incubator's one with enabling the incubator catalog in the Rancher UI
![image](https://user-images.githubusercontent.com/4569037/58747223-bc455080-849a-11e9-9388-1253658a7dba.png)

**Comment by chenjr0719** [comment]
@guangbochen Thanks for the reply.

I think I can use the chart in helm/incubator to deploy Kafka. But it is hard to figure out how to set up all related configuration about external access in Rancher cluster. I hope that I can do this with Rancher catalog because it provides a very easy-to-use UI can instruct me to handle all the configuration.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
