### ISSUE TITLE
vault-operator fails to start etcd

### ISSUE THREAD

**Issue by erSitzt** [rancher/charts#203]
In Rachner 2.2.4 deploying the vault-operator from Rancher-Library fails due to a problem with name resolution when the etcd-operator starts the etcd pods.

The default version for etcd is `v0.8.4`
Changing the version of the etcd image to `v0.9.4` helps to get it started.

**Comment by guangbochen** [comment]
will update in the next version, thanks for the report.

**Comment by guangbochen** [comment]
should be fixed in https://github.com/rancher/charts/tree/master/charts/vault-operator/v0.1.3

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
