### ISSUE TITLE
[rancher-monitoring] Missing Grafana replicas option

### ISSUE THREAD

**Issue by AlexDaichendt** [rancher/charts#2163]
Hey,

it appears the Grafana section in `values.yaml` are missing the option to specify the amount of replicas. Adding `replicas: 3` manually and upgrading the chart simply ignores the set replicas. 

Is this the right repository? Should I rather report this to [prometheus-kube-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)?

Thanks a bunch for any of your time already! 
Have a nice weekend :smiley:

**Comment by aiyengar2** [comment]
The grafana section is missing on the Edit as YAML view since not all options are bubbled up from the subchart to the main chart's values.yaml, but it should be configurable in the Rancher Monitoring chart for as long as the Grafana subchart has supported it.

Given that it has existed from the first chart, this should be configurable on all versions of Monitoring

https://github.com/rancher/charts/blob/093439a5aa32102a64770c0514257aafd6e4b85b/charts/rancher-monitoring/9.4.200/charts/grafana/values.yaml#L20

Closing out this issue.
