### ISSUE TITLE
Error while creating mount source path '/opt/datadog-agent/run'

### ISSUE THREAD

**Issue by gottfrois** [rancher/charts#24]
Hey guys,

Was trying to add this chart to my rancher 2.0.6 cluster running on GKE.
It seems that activating the `collectLogs` boolean option make the sidecar pod fail to run with following event: `Error: failed to start container "datadog": Error response from daemon: error while creating mount source path '/opt/datadog-agent/run': mkdir /opt/datadog-agent: read-only file system`

Here is the complete describe of the pod: https://gist.github.com/gottfrois/b831135e26fd089e8fe72757b6bee12a

```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by guangbochen** [comment]
the hostpath permission issue causes this, on the GKE probably need to use `/var/lib/datadog-agent/logs` other than `/opt/datadog-agent`, will address it in the new release but now you can just use the stable `datadog` chart from the community library.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
