### ISSUE TITLE
NodePort range should not be hardcoded in mariadb template(maybe a few others)

### ISSUE THREAD

**Issue by mmis1000** [rancher/charts#240]
The Node port range of the cluster is actually configurable through the gui

![圖片](https://user-images.githubusercontent.com/2993977/64628174-844b9300-d423-11e9-909e-e514fda6cd99.png)

However, template of mariadb hardcoded the range to 30000-32767

https://github.com/rancher/charts/blob/c093535e15a52a9502123e48dfda8b1ad453016c/charts/mariadb/v4.4.2/questions.yml#L131-L132

Make selecting port outside of this range impossible though gui

(poke around the rancher endpoint from browser devtools works as expected)

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
