### ISSUE TITLE
Fix default kvdb URL in the Portworx chart

### ISSUE THREAD

**Issue by harsh-px** [rancher/charts#307]
Commit https://github.com/rancher/charts/commit/0818be1901a94a64fb91c7e29e4fe0fb199e4cea added 192.168.70.90 as the default etcd for all Portworx clusters. 

Since this is an etcd instance that doesn't exist, all PX installs are now failing.

@guangbochen can you please help revert this commit?

**Comment by guangbochen** [comment]
we have added this commit to address the CI lint failure of protworx as it has blocked other PRs at that time, you can submit a PR against `master` to remove the default `kvdb` value if it is required.

And since the `kvdb` value is not set on default in Rancher's UI so rancher user will still need to add custom endpoints.
![image](https://user-images.githubusercontent.com/4569037/67446045-bca8d880-f641-11e9-8f6a-d1424bda88b9.png)
