### ISSUE TITLE
EFK Chart should provide authentication and security support

### ISSUE THREAD

**Issue by bhagyas** [rancher/charts#323]
https://github.com/rancher/charts/tree/master/charts/efk/v7.3.0 does not seem to provide a mean to configure authentication for the EFK charts.

Contrast this with https://github.com/elastic/helm-charts/tree/master/elasticsearch which provides the examples for setting up security.

Once you install with rancher apps catalog, you also cannot configure using the standard elastic charts, since rancher hides the deployment from helm - preventing it from using any additional scripts/tooling that allows to generate security certificates.

@guangbochen

**Comment by guangbochen** [comment]
You should be able to pass additional values that are not showing by `questions.yml` via `Edit as YAML`, and it is fully customizable of the answers.

But thanks for reporting this to us and will consider exposing those important value by default in the next version, thank you.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
