### ISSUE TITLE
Create Chart for Artifactory x-ray

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/charts#33]
We don't currently have a chart for any scanning mechanisms.  We should create a chart for JFrog x-ray

**Comment by jainishshah17** [comment]
@JasonvanBrackel  You can use this chart to Deploy Xray https://github.com/jfrog/charts/tree/master/stable/xray

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
