### ISSUE TITLE
Has anyone used Drone 2.0.7 

### ISSUE THREAD

**Issue by chinochao** [rancher/charts#351]
I haven't have any luck getting builds to start in the new 2.0.7 template. Is there anything I am missing. I even started the app without kubernetes enabled as true and false to get the agents enabled but it still doesn't build jobs.

The older version of the template are not available anymore. Is there anything I am missing with this new template.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
