### ISSUE TITLE
Update docker chart for k8s 1.17

### ISSUE THREAD

**Issue by lwj5** [rancher/charts#374]
Failed to install app docker-registry. Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by fmax** [comment]
`Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`
same problem with  Kubernetes Version: v1.18.6 

Component | Version
-- | --
Rancher | v2.4.5
User Interface | v2.4.28
Helm | v2.16.8-rancher1

i also tried to update via rancher-cli - but this also fails

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
