### ISSUE TITLE
EFK - ability to add kibana plugins (Logtrail)

### ISSUE THREAD

**Issue by avarabei** [rancher/charts#388]
Currently it is not possible to add custom plugin to kibana. Can this be improved?
I would like to install Logtrail particularly (https://stackoverflow.com/questions/54157370/how-to-use-helm-to-install-kibana-with-the-logtrail-plugin-enabled)

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
