### ISSUE TITLE
Prometheus Chart fails to start when using default storage class nfs-client-provisioner

### ISSUE THREAD

**Issue by totallyGreg** [rancher/charts#40]
Chart runs fine with persistent volume enabled=False  

When Persistent Volume is enabled it fails to start due to the init-chown-data container failing.  
`kubectl --namespace=prometheus logs prometheus-server-78f564dfdb-h6vls -c init-chown-data
chown: /data: Invalid argument
`
Preventing the prometheus and grafana pods from starting.  This appears to be an issue with NFSv4 idmapping issue.  
This is a custom cluster running on hardware on premise and the NFS Server is FreeNAS 11.1U6 and has the "NFSv3 ownership model for NFSv4" option selected but it seems as if the client side also needs to disable nfs4 idmapping
From  https://serverfault.com/questions/718389/chown-or-chgrp-nfsv4-with-idmapd-error-invalid-argument 
it suggests  "options nfs nfs4_disable_idmapping=1" >> /etc/modprobe.d/nfs.conf for RHEL machines.  Since this is busybox I am not sure if the equivalent would be in the container or docker itself that this is defined.

It doesn't appear that any mount options can be specified to the nfs-client-provisioner that will solve this.  At this point it is not clear to me whether this is something that needs to be fixed in the busybox image or the nfs-client-provisioner.  

Being not entirely sure why init-chown-data needs to run at all, I did try to run the chart with the "initChownData.enabled" false but that also failed.  

Likely, not a chart issue per say but I am not sure where else to submit the issue.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
