### ISSUE TITLE
harbor cert pod's registry-ca container failing when installing

### ISSUE THREAD

**Issue by ajureeruja** [rancher/charts#412]
I'm currently trying to deploy Harbor through Rancher Catalog.  The cert pod's registry-ca container is failing with ```MountVolume.SetUp failed for volume "ca-cert" : secret "harbor-p-nfh5j-harbor-ingress" not found```

In looking at the ingress/secret.yaml template, the creation of that secret depends on harbor.autoGenCertForIngress being true.  I selected a certificate to use from the certificate dropdown before deploying Harbor so i'm assuming that is why that would be false.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
