### ISSUE TITLE
EFK.kibana error

### ISSUE THREAD

**Issue by bnnd** [rancher/charts#42]
In kibana,  error.
  http://esteemed-arachnid-elasticsearch.default:9200 
  http://esteemed-arachnid-efk-elasticsearch:9200
```
Unable to connect to Elasticsearch at http://esteemed-arachnid-efk-elasticsearch:9200.
```

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
