### ISSUE TITLE
Harbor: "Expose Service Options" Certificate unable to select anything

### ISSUE THREAD

**Issue by tduvally** [rancher/charts#440]
For all Harbor Proxy Service Types, there is no way to select a Harbor TLS Certificate. It's a chooseList, but is always empty. Creating secrets with certs in advance does not allow this to be populated. Harbor will always create a self-signed cert which can't seem to be replaced. I have valid certs, but I can't get the harbor install to notice them in the WebUI.

cert-manager is not installed, if that matters. Using "Bring your own" certs.

**Comment by tduvally** [comment]
I found this is the Rancher docs: 
Default to string if not specified (current supported types are string, multiline, boolean, int, enum, password, storageclass, hostname, pvc, and secret).

https://rancher.com/docs/rancher/v2.x/en/catalog/creating-apps/#questions-yml

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
