### ISSUE TITLE
Not able to update status section in catalog application

### ISSUE THREAD

**Issue by harshalkwagh** [rancher/charts#474]
I have created a custom rancher catalog
I am able to launch application using my catalog.
But when i go inside application page and check for the status section, it does not show any entry there.
![image](https://user-images.githubusercontent.com/22464777/84476913-737ac700-acac-11ea-9236-80ac32fe3066.png)

I could not find any documentation regarding this in rancher official docs.
Also i launched few apps using library catalog like Prometheus etc. but for them also i could not see any entry in the status section.

Can i get help to understand what exactly this status section is used for and how can i add & update entries in that.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
