### ISSUE TITLE
[charts/efk] how do i set or rotate log size?

### ISSUE THREAD

**Issue by encryptblockr** [rancher/charts#488]
https://github.com/rancher/charts/blob/master/charts/efk/v0.1.3/values.yaml

how do i set a log size to avoid getting storage used up?
i don't need to persist all logs and will like to set a limit to log size or find a way to delete old logs

anyway to set this up?

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
