### ISSUE TITLE
harbor charts environment externalURL doesn't work 

### ISSUE THREAD

**Issue by theWayToAI** [rancher/charts#489]
hi,
I have deployed harbor by using rancher charts 1.3.2, and after deployed it seems everything works fine. I can login my admin by web. But after I execute docker login harbor.xxx.cn(it's my private domain,expose by ingress), i got this error:
`Error response from daemon: Get https://harbor.xxx.cn/v2/: Get https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: EOF`
i have already change my env externalURL to harbor.xxx.cn in question.yaml, but it seems the registry-cm.yaml get this env by value.yaml which defines externalURL as core.harbor.domain?
So i change externalURL from core.harbor.domain to harbor.xxx.cn in config-map manually, and now i can login.
Hope that this value can work in registry-cm.yaml.
Thanks.

**Comment by crazybg321** [comment]
Is there any progress on this. I have been experiencing the same issue and it's quite cumbersome to work around it

**Comment by cxgreat2014** [comment]
Is there any progress on this? I have been experiencing the same issue and it's quite cumbersome to work around it

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
