### ISSUE TITLE
Nextcloud Chart

### ISSUE THREAD

**Issue by clwillingham** [rancher/charts#523]
[Nextcloud](https://nextcloud.com/) would be a useful thing to be able to spin up from within rancher. I managed to get nextcloud running through helm from the official repositories here: https://hub.helm.sh/charts/stable/nextcloud
Unfortunately the official repository is referencing a deprecated mariadb helm chart (also that entire repository is going to be deprecated in a year or so) so the only way I could get the chart to function was by using the internal sqlite database.

**Comment by lucernae** [comment]
You could spin up or tie it with external database.
I did try to deploy nextcloud a couple of weeks ago and tie it with postgres that is spin up using charts too.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
