### ISSUE TITLE
[datadog] DD_SITE not set for agent-clusterchecks-deployment.yaml

### ISSUE THREAD

**Issue by axeal** [rancher/charts#556]
Catalog datadog chart v2.1.2 has same issue reported upstream in https://github.com/helm/charts/issues/19298 This has been fixed in more recent upstream chart versions per https://github.com/helm/charts/blob/master/stable/datadog/templates/agent-clusterchecks-deployment.yaml

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
