### ISSUE TITLE
Keel chart

### ISSUE THREAD

**Issue by rusenask** [rancher/charts#64]
Hello, I am author of Keel - https://github.com/keel-hq/keel and it came to my notice that there are quite a lot of Rancher users using Keel. I think I could make their life easier by adding Keel to the catalog :) 

---

### Short description about Keel

Keel is a stateless, lightweight CD solution that reacts to multiple registry (azure, dockerhub, gitlab, harbor, quay) webhooks, integrates directly into GCR through pubsub and can also do polling. 

It supports updating:
* Deployments
* Daemonsets
* StatefulSets
* Helm charts

Policy driven updates:
* Canonical semver releases (incremental updates based on patch/minor/major versions)
* Regex support
* Glob matching (`glob:build-number-*`)

Main advantages against alternative solutions:
* No CLI required
* No dependencies - single container, uses around 20MB RAM
* Event driven - easy to understand when it works and doesn't get in your way if cluster is on fire 
* Configuration is done in a "self service" manner where developers just add labels or annotations to their manifests that need to be updated:

![Example manifest](https://keel.sh/images/keel-minimal-configuration.png?_sw-precache=0bccaf6f15f6d90197bd60997e98dd85)

**Comment by guangbochen** [comment]
a chart PR would be welcome here and I will review it, thanks.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
