### ISSUE TITLE
EFK config for custom env parameters

### ISSUE THREAD

**Issue by kphunter** [rancher/charts#70]
Rancher: v2.1.1
Catalog: EFK chart 0.1.3

I'm having trouble figuring out how to configure parameters that are not specified for this chart. I'm specifically looking to increase Elasticsearch's default `http.max_content_length` from 100mb to 500mb.

Would I have to start by rebuilding the docker image to achieve this?

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
