### ISSUE TITLE
server.prefixURL and server.baseURL not working

### ISSUE THREAD

**Issue by Annihil8ted** [rancher/charts#76]
Specifying server.prefixURL and server.baseURL results in prometheus-server not being able to startup.

Expected and desired behaving. Get prometheus to deploy at /prometheus endpoint.

**Comment by ihorman** [comment]
got the same issue: changing server.prefixURL to other from default makes local healthcheck receive 404 and server startup is not happening

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
