### ISSUE TITLE
Rancher mixed up integration points 

### ISSUE THREAD

**Issue by WellingtonMan** [rancher/charts#809]
Hi

we have recently added a new user(Cameron Madurai) onto our subatomic project (cib-markets) , also granted him access onto rancher under cb-fx integrators. When the user tries to access the fx integration points, he gets directed to the sigma integration points.

User belongs to these authentication groups
Admin: FXOptions-PROD-ZA-admin-access
User: FXOptions-PROD-ZA-user-access

We not sure what is causing this, please have a look!

Regards
Wellington

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
