### ISSUE TITLE
rancher openebs quey repository issue

### ISSUE THREAD

**Issue by ErroKokkarda** [rancher/charts#824]
Hello,

it seems that when one tries to deploy openebs 2.x there is issue with
quay.io/openebs/xx images

https://github.com/rancher/charts/blob/master/charts/openebs/v2.1.0/questions.yml

there is issue when pulling these images 

but if one does not use quay.io it seems fine 
https://github.com/openebs/charts/issues/161

you can upgrade openebs to 2.x only if you remove v from node disk manager image and remove quay prefix in default images

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
