### ISSUE TITLE
Access to kiali for non-admin users

### ISSUE THREAD

**Issue by chihaiaalex** [rancher/charts#833]
Hello! I'm having issues granting access to Kiali for non-admin users in Rancher 2.5 preview 1.
The docs says that: 

> Your access to the visualizations depend on your role. Grafana and Prometheus are only available for cluster-admin roles. The Kiali UI is available only to cluster-admin by default, but cluster-admin can allow other roles to access them by editing the Istio values.yaml. [https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/#accessing-visualizations](url)

The thing is I can't tell based on the chart what should I edit in the values.yaml for this to work. I've enabled read only mode for Kiali (I want it to be only a visualisation mechanism), but the button for Kiali in the Cluster Explorer  -> Apps -> Istio is disabled.

What I want to achieve finally is the option we had in the 2.4 version:
> Allow all authenticated members to access Kiali and Jaeger UI must be checked on Tools - Istio - Group Access

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
