### ISSUE TITLE
Feature Request:  Prometheus Endpoint for EFK Stack

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/charts#84]
It would be great to have the prometheus endpoint plugin available from within the container so we can get metrics on how the Elastic cluster is performing.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
