### ISSUE TITLE
MariaDB slave healthcheck fails due to 'access denied'

### ISSUE THREAD

**Issue by sn0opy** [rancher/charts#86]
I am running the latest (5.0.9) MariaDB chart on Rancher 2.1.3 on a k8s 1.13 cluster. When configuring, I choosed to have a single-slave setup. Said slave won't come up properly due to the healthcheck using `mysqladmin status` fails. Full error event:

> Readiness probe failed: mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)'

Connecting to said container directly and perfoming the command manually fails with the same error. The MariaDB is started and is awaiting connections.

Haven't tried the Helm chart directly yet.

**Comment by munjal-patel** [comment]
I am also having the same issue.

**Comment by NightDragon1** [comment]
Same here

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
