### ISSUE TITLE
Elastic JVM Heap Size

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/charts#90]
Not sure why we are limited to selecting 512M, 1G or 2G for the JVM heap sized allowed for ElasticSearch in the EFK chart.  2G is really a bare minimum for Elastic, and it really should be pushing 20G - 30G in size.

**Comment by guangbochen** [comment]
Thanks for the feedback and we will add more options of JVM heap size in the next new version release, but for now u can still set custom heap size or any other parameters available in the values.yaml via click ‘edit for as yaml’ button, thanks.

**Comment by MaxDiOrio** [comment]
Thanks.  The edit as yaml is one of the best new features of Rancher.

**Comment by rasert** [comment]
This option is no longer available. Can you please provide a way of setting the JVM Heap size and the Host resource requirements so that I can keep heap 50% of total host memory?

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
